### ISSUE TITLE
Release k-sigs/promo-tools@v4.0.5

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/promo-tools#1197]
### v4.0.5

Issue track for the upcoming release of promo-tools 4.0.5.

Previous promo-tools release cut issue: https://github.com/kubernetes-sigs/promo-tools/issues/941

- [x] Release Prep:  https://github.com/kubernetes-sigs/promo-tools/pull/1198
- [x] Release:  https://github.com/kubernetes-sigs/promo-tools/releases/tag/v4.0.5
- [x] Image promotion:  https://github.com/kubernetes/k8s.io/pull/6371
- [x] Rollout:  https://github.com/kubernetes/test-infra/pull/31813

cc @kubernetes-sigs/release-engineering

**Comment by saschagrunert** [comment]
This seems done, right?
