### ISSUE TITLE
create qualification tests for images in staging

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/promo-tools#144]
As noted in https://github.com/kubernetes/k8s.io/pull/406#pullrequestreview-304685191, the staging image up for promotion should have a link to it being tested (maybe some more thorough e2e tests going through various flags, etc). This could be a Prow postsubmit job. That job could run against `master` branch, and for every update to it:

1. pushes up a new version to the staging repository
2. run various e2e tests (running the same e2e test suite we already have)

Then the logs for this job itself could be linked-to for every promotion PR promoting this newly-tested version to prod.

**Comment by rajibmitra** [comment]
I would like to work on the prow job if its ok @listx   @rikatz

**Comment by rikatz** [comment]
For me it’s ok :)

I just want to follow the work also (as a curious person!)

Em ter, 29 de out de 2019 às 07:28, Rajib Mitra <notifications@github.com>
escreveu:

**Comment by listx** [comment]
Sounds good to me. Please write a design doc of some sort to sketch out your thoughts first before pushing up an implementation. You can then share it with https://groups.google.com/forum/#!newtopic/kubernetes-wg-k8s-infra

**Comment by rikatz** [comment]
@rajibmitra do you need something (any help, insights) to write that document? :)

**Comment by listx** [comment]
/reopen

The work that @yodahekinsew is doing touches on this area, as he is expanding the number of various tests to check against staging images. See https://docs.google.com/document/d/1D5FEU58j3_V8Fxl98I3vcqNCxzpD9cV9Gtpxf9wGO4I/edit#heading=h.4bti0lhcgu9m.

**Comment by rikatz** [comment]
Per past @listx comments:

/reopen
/remove-lifecycle rotten
/lifecycle active

Now I think the bot wont close it again :)

**Comment by rikatz** [comment]
Hum not a member of kubernetes-sigs so not authorized to reopen

@listx feel free to reopen this :)

**Comment by listx** [comment]
@yodahekinsew Please update this issue once the added checks are live.

**Comment by listx** [comment]
/reopen
/remove-lifecycle rotten
/lifecycle active

# Intro

OK so we got bitten by the lack of QA tests for staging images with https://github.com/kubernetes/test-infra/pull/23148 (reverted in https://github.com/kubernetes/test-infra/pull/23151). There are several things going on, but let me capture what's happening today. You can think of this comment as a mini-postmortem doc.

# Current state of affairs

## Step 1: Code changes to CIP repo
We merge PRs into this repo to update the `master` branch. When that branch moves (a PR is merged to improve the CIP tool and other relating things), [post-cip-push-image-cip](https://prow.k8s.io/?job=post-cip-push-image-cip) runs (config [here](https://github.com/kubernetes/test-infra/blob/caeaacec0de5a867e5d420da85c8f69bf33fc1ca/config/jobs/image-pushing/releng/k8s-staging-artifact-promoter.yaml#L31)) and a new image appears in gcr.io/k8s-staging-artifact-promoter/cip-auditor.

## Step 2: Promotion from staging to prod
Later, when the powers that be deem that the image should be promoted to production, we create a PR to "promote the promoter", like [this](https://github.com/kubernetes/k8s.io/pull/2475). When the PR is merged, the staging image is promoted to prod (via [post-k8sio-image-promo](https://github.com/kubernetes/test-infra/blob/caeaacec0de5a867e5d420da85c8f69bf33fc1ca/config/jobs/kubernetes/wg-k8s-infra/trusted/releng/releng-trusted.yaml#L3)).

## Step 3: Update of Prow Job configuration
Finally, we can now also update existing Prow Jobs that rely on the promoter to use this new production version. A PR to update the Prow Jobs is created, to bump the image version used, like [this](https://github.com/kubernetes/test-infra/pull/23148).

# The fire/problem

Now consider https://github.com/kubernetes/test-infra/pull/23148. Alas, it needed to be [reverted](https://github.com/kubernetes/test-infra/pull/23151). The problem (captured in the logs) was that the CLI flag handling logic changed between the old version used prior to this PR (version `v2.4.1`) and the one proposed by this PR (version `v20210805-v1.337.0-136-g8f6bfde`). (Additionally, @justaugustus reported that we also had not yet fixed the `--dry-run` behavior yet in this version, but I won't be going into that here.) So in summary, even if the promoter image *in isolation* was well-formed, its use in the Prow Job configuration was incorrect. That is, https://github.com/kubernetes/test-infra/pull/23148 should have included changes to the CLI arguments passed into the image.

# Proposed changes

So how do we prevent this problem in the future?

Apart from a more formalized process for designating new promoter images for production (involving more review from the Release Engineering group), there are additional changes we can make:

1. We should create a Prow Job configuration test to enforce rules for how we invoke the promoter image (e.g., make sure that the arguments we're passing into the image are correct), so that when we attempt to bump a version of the promoter in a Prow Job, that change can be tested. We can use the pattern of creating a unit test in Prow (see this [example](https://github.com/kubernetes/test-infra/blob/caeaacec0de5a867e5d420da85c8f69bf33fc1ca/config/tests/jobs/jobs_test.go#L362-L414)). This will automatically act as a presubmit for Step 3 above.
2. We can additionally have a similar test (perhaps using https://github.com/GoogleContainerTools/container-structure-test as a framework) to check CLI arguments as part of Step 2. That is, we could have a new presubmit job that watches the promoter's own [promotion manifest file](https://github.com/kubernetes/k8s.io/blob/263de850331a18a032cc104e85d50143d3995c82/k8s.gcr.io/images/k8s-staging-artifact-promoter/images.yaml) and then run a test that performs QA against the to-be-promoted-to-production image. The lack of such a test was the reason why this GitHub issue was originally created. As per the OP, this test *could* be implemented as a postsubmit against the CIP codebase instead of the promoter manifest for it as described earlier, although in the former case we'd have to probably run a sleep loop to wait until there is a staging image available for testing (that is, wait for `post-cip-push-image-cip` to finish before executing).
3. We can also add unit tests in the CIP repo directly that also check for CLI arguments/flag handling. This will force us to bump version numbers, etc. whenever these tests break (or because there are simply newer features). The unit tests here are somewhat removed from the original concern of this postmortem, but they would still bring up issues regarding CLI arguments worth knowing about.

I think we should do all 3 of the above, in the order they are listed. But how can we maximize code reuse across all 3 changes? It would be painful to have 3 separate sets of tests, requiring us to update each of these separately. I assume changes 2 and 3 can somehow share code, but I'm not sure about the first.

**Comment by justaugustus** [comment]
So it's in my queue to help with:
/assign

FYI @kubernetes-sigs/release-engineering on https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/144#issuecomment-893917449.

**Comment by listx** [comment]
@justaugustus I think I can help with adding a unit test in Prow (proposed change 1). I'm going to be working more in Prow anyway so it's a good exercise.

**Comment by tylerferrara** [comment]
Two questions:
Will these proposed solutions get their own issues?
In Step 3, are we suggesting the addition of another verify script to enforce a standard API? If so, I like this idea. As you mentioned, this API definition should be referenced in Step 1. Therefore, changing the API would only require a single file change.

Thinking out loud: In addition, we may want to reference this API in the `README` for new users to rely on specific behavior. New releases could ensure a set of static features, while incrementally adding new flags. This could be thought of as a "core" and "extra" set of features.

**Comment by listx** [comment]
> Two questions:
> Will these proposed solutions get their own issues?

Ideally yes; I'll try to keep this thread synced with any new issues related to this area.

> In Step 3, are we suggesting the addition of another verify script to enforce a standard API? If so, I like this idea. As you mentioned, this API definition should be referenced in Step 1. Therefore, changing the API would only require a single file change.

Yeah we could use some sort of standardized API definition for CIP and related tools. Maybe that "source of truth" will be in the form of a YAML configuration defined for https://github.com/GoogleContainerTools/container-structure-test. (Or is just rolling our own "CLI API" YAML definition better? IDK)

> 
> Thinking out loud: In addition, we may want to reference this API in the `README` for new users to rely on specific behavior. New releases could ensure a set of static features, while incrementally adding new flags. This could be thought of as a "core" and "extra" set of features.

Not sure what you mean by core vs extra features, but yeah if we just have some piece of YAML that defines what the API should be, we can run with it for READMEs, docs, changelogs, etc.
