### ISSUE TITLE
Improved CLI UI/UX

### ISSUE THREAD

**Issue by listx** [kubernetes-sigs/promo-tools#347]
#### Background

Today when a human makes changes to the promoter manifests inside [this folder](https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io/images), they can do it with the [cip-mm](https://pkg.go.dev/k8s.io/release/cmd/cip-mm) tool, or by hand (there is no requirement that they use cip-mm). 

This is an umbrella issue for possible CLI UI/UX improvements to make it easier to reason about changes to promoter manifests.

#### What we need

1. **More information stored in YAMLs (to include child image digests)**: Make the promoter manifests become the single source of truth for child images for so-called "fat manifests", aka "manifest lists". That is, make it so that the auditor does not have to call out to GCR to determine if a child image is tied to an approved parent digest (as seen today in the promoter manifest YAML). This means that promoter manifests **will contain child image information as well when dealing with fat manifests)**.
2. **Interactive cip-mm experience**: Make it easier to browse the existing images in the promoter manifests [folder](https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io/images). For example, it would be great if we could have a CLI that could explore the nested YAML structure of the folder, and also query for the latest images (sort by newest additions), while also integrating with the various staging GCRs out there so that it can be trivial to *interactively* invoke [cip-mm](https://pkg.go.dev/k8s.io/release/cmd/cip-mm) instead of having to invoke it with various flags.
3. **Helper bot messages for changes to promoter manifests (simplified diff)**: Promotion PRs [like this one](https://github.com/kubernetes/k8s.io/commit/56a73ea55d700cd3cc3e1bdd503ab6f65f352b39) are difficult to parse because one cannot immediately see which images are actually being pushed (within the default diff view that GitHub provides). It would be much better to have a bot that sends a message to the PR that summarizes the changes represented in the promotion PR (perhaps even giving opinionated stats about what the previous tag entry was compared to this one, if it follows semver, etc).

#### Why we need this

If we implement points 1 and 2 today, then the auditor scaling issue identified in #259 becomes dramatically simplified (we wouldn't even need to query GCR to figure out which parent image a child image belongs to for fat manifests, greatly simplifying the code, not to mention, increasing robustness and simplicity).

Point 3 is needed to help make promotion PRs less burdensome to review. Just having automated links that can linkify the newly-added image in the PR (as a robot comment), is an improvement.

/cc @tylerferrara @justaugustus

**Comment by puerco** [comment]
These are great ideas. How do you envision # 2 working? A full-fledged curses selector? A search thingie with completion or something like that? Definitely, 3 is badly needed as reviewing promotion PRs with multiple images is not practical, a good example: https://github.com/kubernetes/k8s.io/pull/2232/files

**Comment by listx** [comment]
> How do you envision # 2 working? A full-fledged curses selector? A search thingie with completion or something like that?

A curses-based UI would be a good start. Maybe we can piggy-back on top of existing tools that understand YAML, such as https://www.visidata.org/, although that presents its own set of challenges. Either way, I want a tool that I can use to easily view existing images quickly (e.g., fuzzy-search as I type to filter out those image(s) we care about in the promoter manifests), and also to add new images into the promoter manifests (cip-mm). For adding new images through this new UI, one can imagine browsing a live staging GCR, selecting images, then being able to "commit" or add these selections to the promoter manifests (to send up as a PR).
