### ISSUE TITLE
Auditor not querying GCR

### ISSUE THREAD

**Issue by tylerferrara** [kubernetes-sigs/promo-tools#353]
#### What happened:
The GCP project: `k8s-artifacts-prod` does not appear to show it's GCR API being requested. This is unexpected behavior, as the auditor should be continuously verifying new GCR state changes. When it sees a new image that is not inside k/k8s.io, it consults the GCR to verify this image. However, since there hasn't been ANY queries to GCR in 30+ days, the auditor must not be running correctly.

Related to k/k8s.io issue: [#2364](https://github.com/kubernetes/k8s.io/issues/2364)

#### What you expected to happen:
The API service should show some amount of requests for GCR.

#### How to reproduce it (as minimally and precisely as possible):
N/A 

#### Anything else we need to know?:
![pantheon corp google com_apis_api_containerregistry googleapis com_quotas_project=k8s-artifacts-prod pageState=(%22duration%22_(%22groupValue%22_%22P30D%22,%22customValue%22_null))](https://user-images.githubusercontent.com/20875599/126229173-763d277a-3883-4b3c-8718-a10ce82b062a.png)
![pantheon corp google com_iam-admin_quotas_project=k8s-artifacts-prod pageState=(%22allQuotasTable%22_(%22f%22_%22%255B%257B_22k_22_3A_22Service_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Container%2520Registry%2520API_5C_22_22_2C_22s_22_3At (2)](https://user-images.githubusercontent.com/20875599/126229289-c6fb0321-91a6-4dc7-874e-94f99ef053c3.png)

#### Environment:

- Cloud provider or hardware configuration: GCP
cc: @listx @amwat @justaugustus @kubernetes-sigs/release-engineering

**Comment by listx** [comment]
Thinking about this again, I think it's because the auditor queries the staging GCRs, not prod. See https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/bed8661305e1e325d0dd22b61e0cea2967b0f0e4/legacy/audit/auditor.go#L261-L266. The `subproject` here means the *staging* repo that belongs to the subproject, not production.

**Comment by tylerferrara** [comment]
@listx appears to be correct! [Here](https://github.com/kubernetes-sigs/k8s-container-image-promoter/blob/0d994e8a53682a831224af62b34065ad88442d9a/legacy/dockerregistry/inventory.go#L1591-L1677) we see two functions that make HTTP requests to GCR. I don't believe this would be monitored by the Container Registry API. This would explain why the auditor is not triggering these metrics. This PR #356 looks to gain visibility on this topic by logging total number of GCR requests per 10 min period. This is[ how GCR measures it's quotas](https://cloud.google.com/container-registry/quotas), therefore we can notice how close the auditor is getting to the upper limit of 50,000 requests per 10min within the logs.

**Comment by tylerferrara** [comment]
Deployment of this PR: #383 should help us gain insight into the auditor's network usage.

**Comment by tylerferrara** [comment]
According the the logs, the auditor is periodically restarting.
![restart](https://user-images.githubusercontent.com/20875599/128102000-b780fd35-10ec-4238-8279-1691b82f4cef.png)
It doesn't appear to show any error or failing behavior which makes a strong case that Cloud Run is throttling it. [Auto-scaling](https://cloud.google.com/run/docs/about-instance-autoscaling) is a feature of Cloud Run which may be giving us this unwanted behavior. If we take a look at the metrics, the auditor seems to be using so little CPU and receiving no requests, forcing it to remain idle.
![idle](https://user-images.githubusercontent.com/20875599/128102472-74580369-8614-4131-b30b-6fc963c11ba6.png)
Although [the docs](https://cloud.google.com/run/docs/about-instance-autoscaling#idle-instance) suggest specifying `--min-instances` to remain "_permanently_ available" our efforts to do so, in our deploy script, does not seem to have that effect.

**Comment by tylerferrara** [comment]
We have successfully captured an instance where the Auditor has exceeded quota!

This was during the audit of `mock/kube-scheduler`:
![pantheon corp google com_run_detail_us-central1_cip-auditor_logs_project=k8s-artifacts-prod (2)](https://user-images.githubusercontent.com/20875599/128382817-acbe8555-ed19-47ac-82ed-28a3075df876.png)
