### ISSUE TITLE
Allow explicitly filtering images by name via `kpromo pr --image`

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/promo-tools#479]
#### What would you like to be added:

A way to specify one or more images that should be skipped/excluded when running `kpromo pr`. 

For example:

```
kpromo pr --skip-images capd-manager --fork fabriziopandini --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @vincepri" --tag v1.1.0-beta.1
```

#### Why is this needed:

Some projects such as Cluster API may have tagged images in staging that are only meant for dev/testing purposes and should not be promoted to the prod repo. Having a way to exclude those images would provide an optional way to skip certain images if found, while preserving existing behavior if the flag is not specified.

**Comment by CecileRobertMichon** [comment]
@puerco @justaugustus @fabriziopandini @vincepri thoughts?

**Comment by CecileRobertMichon** [comment]
if there is agreement this would be a desirable addition, I can work on it

**Comment by fabriziopandini** [comment]
+1
thanks for taking care of following up on this @CecileRobertMichon

**Comment by justaugustus** [comment]
> if there is agreement this would be a desirable addition, I can work on it

@CecileRobertMichon -- we'd love for you to take this up, if you have the bandwidth!

While it may feel out of scope for this feature request, I think the first step is to:

1. Merge the functionality of `cip-mm` into `kpromo pr`, and:
2. Deprecate `cip-mm`

Here's a code snippet: https://github.com/kubernetes-sigs/promo-tools/blob/20e4933e593daf0b93362a089cf9ce072ebbd1d1/cmd/cip-mm/main.go#L108-L111

I'd suggest supporting filtering by explicit image (the functionality already exists in `cip-mm`), as opposed to excluding images.

Let me know if that sounds good :)

**Comment by CecileRobertMichon** [comment]
Can you clarify what you mean by "Merge the functionality of cip-mm into kpromo pr"? What functionality is in cip-mm that's missing in kpromo pr? How is that a prerequisite for adding an --image flag to kpromo pr? 

I'm not familiar with cip-mm so trying to figure out how much scope we're talking about here before I sign up for this.

**Comment by justaugustus** [comment]
> Can you clarify what you mean by "Merge the functionality of cip-mm into kpromo pr"?

Essentially ensuring `kpromo pr` includes the features of `cip-mm`.

> What functionality is in cip-mm that's missing in kpromo pr? How is that a prerequisite for adding an --image flag to kpromo pr?

`cip-mm` is a predecessor to `kpromo pr` (fka `krel promote-images`) and the lens of creation for the two of them was slightly different.

`cip-mm` lens was "As any user, I would like to take a promotion manifest and grow it, by adding entries filtered by image name, digest, or tag."

`krel promote-images` lens was "As a Kubernetes Release Manager, I would like to semi-automatically create a PR that grows the `k8s-staging-kubernetes` manifest to include all images (restricted to the upcoming/in-progress release tag) e.g., `{kube-apiserver,kube-controller-manager,kube-proxy}:v1.24.0`".

So the scopes were different, but there's overlapping functionality.
The `--filter_image` flag for `cip-mm` is what you're looking for here.

**Comment by CecileRobertMichon** [comment]
I opened #482 which reuses the existing "filter by image" functionality in the GrowManifest options to expose it in `kpromo pr`. That fixes our specific use case in this issue and gets `kpromo pr` to including features of `cip-mm`. 

In order to fully deprecate `cip-mm` I believe we'd still need to expose filtering by digest but that's a separate feature so it should probably be its own PR and I'd prefer to keep the scope limited for now.
