### ISSUE TITLE
cip-mm promotes platform variants even when not needed

### ISSUE THREAD

**Issue by palnabarun** [kubernetes-sigs/promo-tools#484]
#### What happened:

When using `cip-mm` to update manifest for image promotion, the platform variants are added to the promotion configuration even when not needed.

Ref: https://github.com/kubernetes/k8s.io/pull/3268#discussion_r786509710

#### What you expected to happen:

The variants should not be populated.

#### How to reproduce it (as minimally and precisely as possible):

Run `cip-mm` on https://github.com/kubernetes/k8s.io at `d139636177b4ef063bd43bb42bdc6e6468b06d12`.

```
$ 
$ cip-mm \
  --base_dir k8s.gcr.io \
  --staging_repo gcr.io/k8s-staging-build-image \
  --filter_tag v2.3.1-go1.17.6-bullseye.0 \
  --filter_tag v2.3.1-go1.16.13-buster.0
```

#### Anything else we need to know?:

`cip-mm` was installed using `go install sigs.k8s.io/promo-tools/v3/cmd/cip-mm@latest`

#### Environment:

- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): macOS Monterey
- Kernel (e.g. `uname -a`): `Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64`
- Others: None

**Comment by saschagrunert** [comment]
I always thought that this was a feature. We probably should stop building them to staging if we don't promote those variants in any case.
