### ISSUE TITLE
cannot use kpromo when have tag like 1.18-bullseye-0

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/promo-tools#520]
#### What happened:

When we have a tag that is missing the patch version kpromo complaints

```
$ kpromo pr --fork cpanato --interactive --project releng --tag 1.18-bullseye-0
FATA checking command line options: verifying tag: 1.18-bullseye-0: No Major.Minor.Patch elements found
```

If this is expected by design we need to remember to always build tag images with a valid semver

cc @justaugustus 

#### What you expected to happen:

It should be able to parse special tags or allow via flag to ignore that

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by wespanther** [comment]
Looking through the `kpromo pr` code, this will fail for any tag that isn't strictly a SemVer:

- https://github.com/kubernetes-sigs/promo-tools/blob/a0fcea2171effe4df30597817c9da4bcb3a184ac/cmd/kpromo/cmd/pr/pr.go#L86-L91

This seems to apply to image names with a valid SemVer suffix (e.g. buster-v1.0.0):

```
wpanther@wpanther > ~/kubernetes-sigs/promo-tools > main > $(go env GOPATH)/bin/kpromo pr --fork=wespanther --tag=buster-v1.0.0 --project=build-image
FATA checking command line options: verifying tag: buster-v1.0.0: Invalid character(s) found in major number "buster-v1"
```

**Comment by wespanther** [comment]
Looks like @justaugustus has support for non-SemVer tags on the deprecation punchlist, so I assume this should be changed:

https://github.com/kubernetes-sigs/promo-tools/blob/a0fcea2171effe4df30597817c9da4bcb3a184ac/cmd/kpromo/cmd/pr/pr.go#L397
