### ISSUE TITLE
Copy images to AWS regions

### ISSUE THREAD

**Issue by jaypipes** [kubernetes-sigs/promo-tools#533]
image-promoter needs the ability to copy to AWS regions, based on a per-region bucket scheme.

Related: https://github.com/kubernetes-sigs/oci-proxy/issues/39

@jaypipes coordinating with @Verolop and @puerco from Release Engineering

**Comment by BenTheElder** [comment]
xref: https://kubernetes.slack.com/archives/CCK68P2Q2/p1649978570481889?thread_ts=1649976555.356029&cid=CCK68P2Q2

So the layout is like `$bucket/containers/image/sha256:$blobhash`  for all the blobs in GCS.

@ameukam has already run a sync between the GCS behind [k8s.gcr.io](http://k8s.gcr.io/) and an s3 bucket.

If we can have the promoter promote digests in the manifest to paths like this in a bucket, then once that's enabled for a bucket we just need to run a backfill sync once, and we don't need any code for the backfill, it's just gsutil rsync gs://us.k8s-artifacts-prod `s3://$bucket`.

This is also pretty easy to redirect to in oci-proxy statelessly.

**Comment by Riaankl** [comment]
/remove-lifecycle stale

@BenTheElder should we keep this open to drive changes to the promotor to push to the S3 buckets or would the process of periodic syncing the bucket with GCS be sufficient?

**Comment by Riaankl** [comment]
Resolved by https://github.com/kubernetes/k8s.io/pull/4118
/close
