### ISSUE TITLE
kpromo pr will ignore all images unless specifying all flags

### ISSUE THREAD

**Issue by puerco** [kubernetes-sigs/promo-tools#546]
#### What happened:

When running `kpromo` to pr changes to manifests of new images, the `pr` subcommand will ignore the images.

#### What you expected to happen:
This command should notice the secified tags and include the images in the modified manifests.

```
kpromo pr --fork=puerco --interactive=true --tag="v1.21.12,v1.21.13-rc.0"

```

#### Anything else we need to know?:

If you run it specifying all flags, the PR goes through as expected:

```
kpromo pr --fork=puerco --interactive=true --tag="v1.21.12,v1.21.13-rc.0"  --reviewers="" --image="" --digests="" 
```

#### Environment:

kpromo v3.4.1

**Comment by saschagrunert** [comment]
/help

@kubernetes-sigs/release-engineering anyone wants to pick this up?

**Comment by palnabarun** [comment]
/assign

Let me take a dig.
