### ISSUE TITLE
Stop using docker-credential-gcloud for promotion (it is slow)

### ISSUE THREAD

**Issue by jonjohnsonjr** [kubernetes-sigs/promo-tools#631]
#### What would you like to be added:

When calling `google.{Walk,List}`, you're already [using `gcrane.Keychain`](https://github.com/kubernetes-sigs/promo-tools/blob/72771b9e37741391bd729a8d52a5c83d1f09036d/internal/legacy/dockerregistry/inventory.go#L755).

You should do the same thing when calling `crane.Copy` [here](https://github.com/kubernetes-sigs/promo-tools/blob/72771b9e37741391bd729a8d52a5c83d1f09036d/internal/legacy/dockerregistry/inventory.go#L1753).

#### Why is this needed:

The `docker-credential-gcloud` helper is slow:

```
$ time echo 'gcr.io' | docker-credential-gcloud get >/dev/null

real	0m0.756s
user	0m0.670s
sys	0m0.083s
```

Assuming [this docker config file](https://github.com/kubernetes-sigs/promo-tools/blob/main/docker/config.json) is used for the promo jobs, `docker-credential-gcloud` is invoked every time you call `crane.Copy`, whereas `gcrane.Keychain` will attempt to find application default credentials in the environment (which is much faster than invoking gcloud) or fall back to gcloud (once!) and cache the result across calls until it needs to be refreshed.

**Comment by BenTheElder** [comment]
I think this was closed by #609 
/close
