### ISSUE TITLE
ParseSnapshot should use a yaml library

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/promo-tools#633]
#### What happened:

`ParseSnapshot` contains a sort of bespoke parser for the yaml format instead of parsing from yaml to a struct with a package like sigs.k8s.io/yaml and then further extracting what we need from the structure.

https://github.com/kubernetes-sigs/promo-tools/blob/72771b9e37741391bd729a8d52a5c83d1f09036d/internal/legacy/dockerregistry/inventory.go#L2352

code like this is brittle and unnecessarily complex, it could be broken by an otherwise perfectly valid source file:
https://github.com/kubernetes-sigs/promo-tools/blob/72771b9e37741391bd729a8d52a5c83d1f09036d/internal/legacy/dockerregistry/inventory.go#L2388-L2390

#### What you expected to happen:

use a robust yaml parsing library

#### How to reproduce it (as minimally and precisely as possible):

N/A

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

Thanks @jonjohnsonjr for pointing this out!

**Comment by cpanato** [comment]
i think we can close this as this function was removed in https://github.com/kubernetes-sigs/promo-tools/pull/799

if that is not correct, please reopen

/close
