### ISSUE TITLE
kpromo should pass environment variables to git

### ISSUE THREAD

**Issue by mrueg** [kubernetes-sigs/promo-tools#782]
#### What happened:
Depending on how you treat this, it could also be a feature request.

Trying to set `GIT_COMMITTER_EMAIL` and `GIT_AUTHOR_EMAIL`  when calling kpromo

https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

#### What you expected to happen:
 Author / Committer emails are set based on the kpromo call

#### How to reproduce it (as minimally and precisely as possible):

GIT_COMMITTER_EMAIL="test@example.com" GIT_AUTHOR_EMAIL="test@example.com" kpromo pr --fork test -i --project your-project  --t=my-tag --image="" --digests=""

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`): 6.1
- Others: -

**Comment by mrueg** [comment]
Looking at the implementation, it seems like this is currently not possible with go-git. https://github.com/go-git/go-git/issues/401

**Comment by cpanato** [comment]
i think we can close this, the PR is merged and will need a new release from this side, but i will do this week

**Comment by mrueg** [comment]
Thanks @cpanato sounds good to me!
